[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https://github.com https://linkedin.com https://twitter.com https://instagram.com; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://api.emailjs.com https://generativelanguage.googleapis.com; frame-ancestors 'none';"
    Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200